# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='product.proto',
  package='product',
  syntax='proto3',
  serialized_options=b'\242\002\005hsblc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rproduct.proto\x12\x07product\"!\n\x11GetProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x11SetProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x12GetProductResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12SetProductResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x13GetBrandNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x13SetBrandNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x14GetBrandNameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14SetBrandNameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb9\x02\n\x07Product\x12G\n\ngetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\"\x00\x12G\n\nsetProduct\x12\x1a.product.SetProductRequest\x1a\x1b.product.SetProductResponse\"\x00\x12M\n\x0cgetBrandName\x12\x1c.product.GetBrandNameRequest\x1a\x1d.product.GetBrandNameResponse\"\x00\x12M\n\x0csetBrandName\x12\x1c.product.SetBrandNameRequest\x1a\x1d.product.SetBrandNameResponse\"\x00\x42\x08\xa2\x02\x05hsblcb\x06proto3'
)




_GETPRODUCTREQUEST = _descriptor.Descriptor(
  name='GetProductRequest',
  full_name='product.GetProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='product.GetProductRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_SETPRODUCTREQUEST = _descriptor.Descriptor(
  name='SetProductRequest',
  full_name='product.SetProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='product.SetProductRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=94,
)


_GETPRODUCTRESPONSE = _descriptor.Descriptor(
  name='GetProductResponse',
  full_name='product.GetProductResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='product.GetProductResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=133,
)


_SETPRODUCTRESPONSE = _descriptor.Descriptor(
  name='SetProductResponse',
  full_name='product.SetProductResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='product.SetProductResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=172,
)


_GETBRANDNAMEREQUEST = _descriptor.Descriptor(
  name='GetBrandNameRequest',
  full_name='product.GetBrandNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='product.GetBrandNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=209,
)


_SETBRANDNAMEREQUEST = _descriptor.Descriptor(
  name='SetBrandNameRequest',
  full_name='product.SetBrandNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='product.SetBrandNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=246,
)


_GETBRANDNAMERESPONSE = _descriptor.Descriptor(
  name='GetBrandNameResponse',
  full_name='product.GetBrandNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='product.GetBrandNameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=287,
)


_SETBRANDNAMERESPONSE = _descriptor.Descriptor(
  name='SetBrandNameResponse',
  full_name='product.SetBrandNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='product.SetBrandNameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=328,
)

DESCRIPTOR.message_types_by_name['GetProductRequest'] = _GETPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['SetProductRequest'] = _SETPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['GetProductResponse'] = _GETPRODUCTRESPONSE
DESCRIPTOR.message_types_by_name['SetProductResponse'] = _SETPRODUCTRESPONSE
DESCRIPTOR.message_types_by_name['GetBrandNameRequest'] = _GETBRANDNAMEREQUEST
DESCRIPTOR.message_types_by_name['SetBrandNameRequest'] = _SETBRANDNAMEREQUEST
DESCRIPTOR.message_types_by_name['GetBrandNameResponse'] = _GETBRANDNAMERESPONSE
DESCRIPTOR.message_types_by_name['SetBrandNameResponse'] = _SETBRANDNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetProductRequest = _reflection.GeneratedProtocolMessageType('GetProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetProductRequest)
  })
_sym_db.RegisterMessage(GetProductRequest)

SetProductRequest = _reflection.GeneratedProtocolMessageType('SetProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPRODUCTREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.SetProductRequest)
  })
_sym_db.RegisterMessage(SetProductRequest)

GetProductResponse = _reflection.GeneratedProtocolMessageType('GetProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTRESPONSE,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetProductResponse)
  })
_sym_db.RegisterMessage(GetProductResponse)

SetProductResponse = _reflection.GeneratedProtocolMessageType('SetProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETPRODUCTRESPONSE,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.SetProductResponse)
  })
_sym_db.RegisterMessage(SetProductResponse)

GetBrandNameRequest = _reflection.GeneratedProtocolMessageType('GetBrandNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBRANDNAMEREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetBrandNameRequest)
  })
_sym_db.RegisterMessage(GetBrandNameRequest)

SetBrandNameRequest = _reflection.GeneratedProtocolMessageType('SetBrandNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETBRANDNAMEREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.SetBrandNameRequest)
  })
_sym_db.RegisterMessage(SetBrandNameRequest)

GetBrandNameResponse = _reflection.GeneratedProtocolMessageType('GetBrandNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBRANDNAMERESPONSE,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetBrandNameResponse)
  })
_sym_db.RegisterMessage(GetBrandNameResponse)

SetBrandNameResponse = _reflection.GeneratedProtocolMessageType('SetBrandNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETBRANDNAMERESPONSE,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.SetBrandNameResponse)
  })
_sym_db.RegisterMessage(SetBrandNameResponse)


DESCRIPTOR._options = None

_PRODUCT = _descriptor.ServiceDescriptor(
  name='Product',
  full_name='product.Product',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=331,
  serialized_end=644,
  methods=[
  _descriptor.MethodDescriptor(
    name='getProduct',
    full_name='product.Product.getProduct',
    index=0,
    containing_service=None,
    input_type=_GETPRODUCTREQUEST,
    output_type=_GETPRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setProduct',
    full_name='product.Product.setProduct',
    index=1,
    containing_service=None,
    input_type=_SETPRODUCTREQUEST,
    output_type=_SETPRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getBrandName',
    full_name='product.Product.getBrandName',
    index=2,
    containing_service=None,
    input_type=_GETBRANDNAMEREQUEST,
    output_type=_GETBRANDNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setBrandName',
    full_name='product.Product.setBrandName',
    index=3,
    containing_service=None,
    input_type=_SETBRANDNAMEREQUEST,
    output_type=_SETBRANDNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCT)

DESCRIPTOR.services_by_name['Product'] = _PRODUCT

# @@protoc_insertion_point(module_scope)
