# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supplier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='supplier.proto',
  package='supplier',
  syntax='proto3',
  serialized_options=b'\242\002\005hsblc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esupplier.proto\x12\x08supplier\" \n\x10GetSourceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x10SetSourceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x11GetSourceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x11SetSourceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9a\x01\n\x08Supplier\x12\x46\n\tgetSource\x12\x1a.supplier.GetSourceRequest\x1a\x1b.supplier.GetSourceResponse\"\x00\x12\x46\n\tsetSource\x12\x1a.supplier.SetSourceRequest\x1a\x1b.supplier.SetSourceResponse\"\x00\x42\x08\xa2\x02\x05hsblcb\x06proto3'
)




_GETSOURCEREQUEST = _descriptor.Descriptor(
  name='GetSourceRequest',
  full_name='supplier.GetSourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='supplier.GetSourceRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=60,
)


_SETSOURCEREQUEST = _descriptor.Descriptor(
  name='SetSourceRequest',
  full_name='supplier.SetSourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='supplier.SetSourceRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=94,
)


_GETSOURCERESPONSE = _descriptor.Descriptor(
  name='GetSourceResponse',
  full_name='supplier.GetSourceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='supplier.GetSourceResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=132,
)


_SETSOURCERESPONSE = _descriptor.Descriptor(
  name='SetSourceResponse',
  full_name='supplier.SetSourceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='supplier.SetSourceResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['GetSourceRequest'] = _GETSOURCEREQUEST
DESCRIPTOR.message_types_by_name['SetSourceRequest'] = _SETSOURCEREQUEST
DESCRIPTOR.message_types_by_name['GetSourceResponse'] = _GETSOURCERESPONSE
DESCRIPTOR.message_types_by_name['SetSourceResponse'] = _SETSOURCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSourceRequest = _reflection.GeneratedProtocolMessageType('GetSourceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSOURCEREQUEST,
  '__module__' : 'supplier_pb2'
  # @@protoc_insertion_point(class_scope:supplier.GetSourceRequest)
  })
_sym_db.RegisterMessage(GetSourceRequest)

SetSourceRequest = _reflection.GeneratedProtocolMessageType('SetSourceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSOURCEREQUEST,
  '__module__' : 'supplier_pb2'
  # @@protoc_insertion_point(class_scope:supplier.SetSourceRequest)
  })
_sym_db.RegisterMessage(SetSourceRequest)

GetSourceResponse = _reflection.GeneratedProtocolMessageType('GetSourceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSOURCERESPONSE,
  '__module__' : 'supplier_pb2'
  # @@protoc_insertion_point(class_scope:supplier.GetSourceResponse)
  })
_sym_db.RegisterMessage(GetSourceResponse)

SetSourceResponse = _reflection.GeneratedProtocolMessageType('SetSourceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETSOURCERESPONSE,
  '__module__' : 'supplier_pb2'
  # @@protoc_insertion_point(class_scope:supplier.SetSourceResponse)
  })
_sym_db.RegisterMessage(SetSourceResponse)


DESCRIPTOR._options = None

_SUPPLIER = _descriptor.ServiceDescriptor(
  name='Supplier',
  full_name='supplier.Supplier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=173,
  serialized_end=327,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSource',
    full_name='supplier.Supplier.getSource',
    index=0,
    containing_service=None,
    input_type=_GETSOURCEREQUEST,
    output_type=_GETSOURCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setSource',
    full_name='supplier.Supplier.setSource',
    index=1,
    containing_service=None,
    input_type=_SETSOURCEREQUEST,
    output_type=_SETSOURCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUPPLIER)

DESCRIPTOR.services_by_name['Supplier'] = _SUPPLIER

# @@protoc_insertion_point(module_scope)
